---
- name: Teams
  hosts: localhost
  connection: local

  tasks:


  - name: Teams
    office_365_connector_card:
      webhook: webhook url
      text: "Here is your newly deployed tomcat server URL {{ teamsMsgToSend }} "

  - name: Dump public IP for VM which will be created
    debug:
        msg: "The Message is  {{ teamsMsgToSend }}."
